export const INSURANCE_COMPANIES = [
  "New India Assurance Company",
  "National Insurance Company",
  "Oriental Insurance Company",
  "United India Insurance Company",
  "Bajaj Allianz General Insurance",
  "ICICI Lombard General Insurance",
  "HDFC ERGO General Insurance",
  "Tata AIG General Insurance",
  "Reliance General Insurance",
  "IFFCO Tokio General Insurance",
  "SBI General Insurance",
  "Cholamandalam MS General Insurance",
  "Future Generali India Insurance",
  "Royal Sundaram General Insurance",
  "Shriram General Insurance",
  "Magma HDI General Insurance",
  "Liberty General Insurance",
  "Raheja QBE General Insurance",
  "Acko General Insurance",
  "Go Digit General Insurance",
  "Navi General Insurance",
  "Zuno General Insurance",
  "Kotak Mahindra General Insurance",
  "Universal Sompo General Insurance",
  "Zurich Kotak General Insurance",
  "Kshema General Insurance",
] as const;
